/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/apple.gltf')

  useFrame(() => {
    const a = window.pageYOffset;
    const rx = a * -0.005;
    group.current.rotation.x = rx;

    group.current.position.y = a * -0.01;

    const ry = a * 0.001;
    group.current.rotation.y = ry;
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 50, 20]} scale={1.2}>
        <mesh geometry={nodes.apple_1.geometry} material={materials['Default OBJ']} />
        <mesh geometry={nodes.apple_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.apple_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/apple.gltf')