/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/plate.gltf')

  useFrame(() => {
    const b = window.pageYOffset;
    const rx = b * 0.0002;
    group.current.rotation.x = rx;

    group.current.position.y = b * -0.0014;

    const ry = b * -0.0001;
    group.current.rotation.y = ry;
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-4.8, 2.7, 0]} position={[-3.8, 0, 0]} scale={1}>
        <mesh geometry={nodes.plate.geometry} material={materials['Material.001']} rotation={[0, 3, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/plate.gltf')
