/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/table.gltf')

  useFrame(() => {
    const a = window.pageYOffset;
    const rx = a * -0.005;
    group.current.rotation.x = rx;

    const ry = a * 0.001;
    group.current.rotation.y = ry;
  })

  return (
    <group ref={group} {...props} dispose={null} scale={1.2}>
      <mesh
        geometry={nodes.table.geometry}
        material={materials['Material.001']}
        position={[0, 0.1, 0]}
        rotation={[3.15, 0, 0]}
        scale={[1.5, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/table.gltf')
